name: Basic Java Build
on: push

jobs:
  build:
    # runs-on: ubuntu-22.04
    runs-on: [self-hosted]
    name: Run basic build
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Show me your teeth
      run: |
        echo "Hello from Runner"
        echo "PWD:"
        pwd
        echo "HOSTNAME:"
        hostname
    - name: Build with Maven
      run: mvn -B verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SECSYLW: ${{ secrets.SECSYLW_TOKEN }}
  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run sec scans boilerplate
    steps:
      - uses: actions/checkout@v2
        name: Checkout
