name: Reusable workflow example

on: 
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  call-workflow-passing-data:
    uses: sylweltan/actions-devsecops/.github/workflows/basic-build.yaml@master
    with:
      config-path: .github/labeler.yaml
    secrets:
      secsylwtoken: ${{ secrets.anotherSecret }}
